# Codecov should always pass. Used to show code coverage only
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 70...95
  status:
    project:
      default:
        # basic
        target: 1
        threshold: 0
