# Codecov should always pass. Used to show code coverage only
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 70...95
  status:
    project:
      default:
        # basic
        # target: 90
        # threshold: 1
        # Always succeed
        if_ci_failed: success #success, failure, error, ignore
